SystemOrganization addCategory: #'GT-CollaborateOld-FogBugz'!
SystemOrganization addCategory: 'GT-CollaborateOld-FogBugz-Announcement'!
SystemOrganization addCategory: 'GT-CollaborateOld-FogBugz-Dialog'!
SystemOrganization addCategory: 'GT-CollaborateOld-FogBugz-Filters'!
SystemOrganization addCategory: 'GT-CollaborateOld-FogBugz-Model'!
SystemOrganization addCategory: 'GT-CollaborateOld-FogBugz-Tests'!
