SystemOrganization addCategory: #'GT-Collaborate-UI-Brick-Basic'!
SystemOrganization addCategory: 'GT-Collaborate-UI-Brick-Basic-Announcement'!
SystemOrganization addCategory: 'GT-Collaborate-UI-Brick-Basic-Core'!
SystemOrganization addCategory: 'GT-Collaborate-UI-Brick-Basic-Model'!
SystemOrganization addCategory: 'GT-Collaborate-UI-Brick-Basic-Obsolete'!
SystemOrganization addCategory: 'GT-Collaborate-UI-Brick-Basic-Theme'!
SystemOrganization addCategory: 'GT-Collaborate-UI-Brick-Basic-Widgets'!
