SystemOrganization addCategory: #'GT-Collaborate-Basic'!
SystemOrganization addCategory: 'GT-Collaborate-Basic-Abstract'!
SystemOrganization addCategory: 'GT-Collaborate-Basic-Announcement'!
SystemOrganization addCategory: 'GT-Collaborate-Basic-Core'!
SystemOrganization addCategory: 'GT-Collaborate-Basic-Developer'!
SystemOrganization addCategory: 'GT-Collaborate-Basic-Model'!
SystemOrganization addCategory: 'GT-Collaborate-Basic-Obsolete'!
SystemOrganization addCategory: 'GT-Collaborate-Basic-Traits'!
