SystemOrganization addCategory: #'GT-Collaborate'!
SystemOrganization addCategory: 'GT-Collaborate-Abstract'!
SystemOrganization addCategory: 'GT-Collaborate-Announcement'!
SystemOrganization addCategory: 'GT-Collaborate-Core'!
SystemOrganization addCategory: 'GT-Collaborate-Developer'!
SystemOrganization addCategory: 'GT-Collaborate-Model'!
SystemOrganization addCategory: 'GT-Collaborate-Obsolete'!
SystemOrganization addCategory: 'GT-Collaborate-Traits'!
