SystemOrganization addCategory: #'GT-Collaborate-PharoSprint'!
SystemOrganization addCategory: 'GT-Collaborate-PharoSprint-Announcement'!
SystemOrganization addCategory: 'GT-Collaborate-PharoSprint-Model'!
SystemOrganization addCategory: 'GT-Collaborate-PharoSprint-State'!
SystemOrganization addCategory: 'GT-Collaborate-PharoSprint-Tests'!
SystemOrganization addCategory: 'GT-Collaborate-PharoSprint-Trantor'!
SystemOrganization addCategory: 'GT-Collaborate-PharoSprint-UI'!
