SystemOrganization addCategory: #'GT-Collaborate-FogBugz'!
SystemOrganization addCategory: 'GT-Collaborate-FogBugz-Commands'!
SystemOrganization addCategory: 'GT-Collaborate-FogBugz-Dialog'!
SystemOrganization addCategory: 'GT-Collaborate-FogBugz-Examples'!
SystemOrganization addCategory: 'GT-Collaborate-FogBugz-Model'!
SystemOrganization addCategory: 'GT-Collaborate-FogBugz-Network'!
SystemOrganization addCategory: 'GT-Collaborate-FogBugz-Settings'!
SystemOrganization addCategory: 'GT-Collaborate-FogBugz-Tests'!
