SystemOrganization addCategory: #'GT-Collaborate-UI-Brick'!
SystemOrganization addCategory: 'GT-Collaborate-UI-Brick-Announcement'!
SystemOrganization addCategory: 'GT-Collaborate-UI-Brick-Core'!
SystemOrganization addCategory: 'GT-Collaborate-UI-Brick-Model'!
SystemOrganization addCategory: 'GT-Collaborate-UI-Brick-Obsolete'!
SystemOrganization addCategory: 'GT-Collaborate-UI-Brick-Theme'!
SystemOrganization addCategory: 'GT-Collaborate-UI-Brick-Widgets'!
